controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    joints:
      - shoulder_yaw_joint
      - shoulder_pitch_joint
      - elbow_joint
      - wrist_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    constraints:
      stopped_velocity_tolerance: 0.05
      goal_time: 0.0

joint_state_broadcaster:
  ros__parameters:
    use_sim_time: true